support for Mongoid 7
frodsan/mongoid-minitest pull request #24
Opened 2018-05-01 18:50 UTC by tomasc

2018-05-02 10:38 UTC, tomasc commented
@frodsan @gr4y @chancancode @prasadsurase @rmm5t can we get this merged please and have a new gem out? Would be fantastic to be able to use `mongoid-minitest` with the new Mongoid 7. Thank you!

2018-05-02 15:10 UTC, rmm5t requested changes
Overall looks good upon a quick pass. Just one minor change to the gemspec, and I think we can get this merged in.

2018-05-02 15:10 UTC, rmm5t commented on mongoid-minitest.gemspec
> +  gem.add_dependency 'mongoid' , '>= 3', '<= 7.0'
Shouldn't this be `'>=3', '< 8.0'`?

2018-05-02 15:34 UTC, tomasc reviewed
Fine with me, will amend

2018-05-02 16:44 UTC, tomasc commented
@rmm5t updated, ready for a merge. Thank you.

2018-05-02 18:50 UTC, rmm5t approved these changes

2018-05-02 18:51 UTC, merged

2018-05-02 19:04 UTC, rmm5t commented
[v1.2.0 just released](https://rubygems.org/gems/mongoid-minitest)

Thanks for the help! 🍻

2018-05-03 05:08 UTC, tomasc commented
Great, thank you!